const test = document.getElementById("p")
console.log(test.childNodes)
console.log(test.firstChild)
console.log(test.lastChild)
console.log(test.hasChildNodes)
console.log(test.nextSibling)
console.log(test.previousSibling)
console.log(test.parentNode)